apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  local:
    push: false # This is the default value. Won't push the image to a registry.
  artifacts:
    - image: khaftab/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: # mnaual will not build the image if the source files change. It will only sync the files. Ouiside of the sync block, the image will be built if the source files change. i.e. pakcage.json, tsconfig.json, etc.
          - src: "src/**/*.ts"
            dest: .
    - image: khaftab/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khaftab/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khaftab/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khaftab/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khaftab/queue
      context: queue
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
