apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      # initContainers:
      #   - name: wait-for-nats
      #     image: busybox
      #     command:
      #       [
      #         "sh",
      #         "-c",
      #         "until nslookup nats-srv.default.svc.cluster.local; do echo waiting for nats; sleep 2; done;",
      #       ]
      #   - name: wait-for-auth-mongo
      #     image: busybox
      #     command:
      #       [
      #         "sh",
      #         "-c",
      #         "until nslookup auth-mongo-srv.default.svc.cluster.local; do echo waiting for mongodb; sleep 2; done;",
      #       ]
      containers:
        - name: auth
          image: khaftab/auth
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-srv:27017/auth
            - name: ORIGIN_URL
              valueFrom:
                secretKeyRef:
                  name: origin-url
                  key: ORIGIN_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TIXBEE_SOURCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logtail-secret
                  key: TIXBEE_SOURCE_TOKEN
            - name: SERVICE_NAME
              value: auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000 # Port exposed by the service
      targetPort: 3000
