apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup nats-srv.default.svc.cluster.local; do echo waiting for nats; sleep 2; done;",
            ]
        - name: wait-for-expiration-redis
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup expiration-redis-srv.default.svc.cluster.local; do echo waiting for redis; sleep 2; done;",
            ]
      containers:
        - name: expiration
          image: khaftab/expiration
          env:
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: REDIS_PORT
              value: "6379"
            - name: TIXBEE_SOURCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logtail-secret
                  key: TIXBEE_SOURCE_TOKEN
            - name: SERVICE_NAME
              value: expiration
