apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: khaftab/payments
          env:
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: SERVICE_NAME
              value: payments
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_WEBHOOK_SECRET
            - name: TIXBEE_SOURCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logtail-secret
                  key: TIXBEE_SOURCE_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
