apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup nats-srv.default.svc.cluster.local; do echo waiting for nats; sleep 2; done;",
            ]
      containers:
        - name: queue
          image: khaftab/queue
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: ORIGIN_URL
              valueFrom:
                secretKeyRef:
                  name: origin-url
                  key: ORIGIN_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TIXBEE_SOURCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logtail-secret
                  key: TIXBEE_SOURCE_TOKEN
            - name: SERVICE_NAME
              value: queue
---
apiVersion: v1
kind: Service
metadata:
  name: queue-srv
spec:
  type: ClusterIP
  selector:
    app: queue
  ports:
    - name: queue
      protocol: TCP
      port: 3000
      targetPort: 3000
