name: expiration-deploy

on:
  push:
    branches:
      - main
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tixbee-github-env
    steps:
      - uses: actions/checkout@v4

      # Login to Docker Hub using the official action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for better build performance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push in a single step
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./expiration
          push: true
          tags: khaftab/expiration:latest,khaftab/expiration:${{ github.sha }}

        # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      # Get GKE Credentials
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      # Restart deployment
      - name: Restart Deployment
        run: kubectl rollout restart deployment expiration-depl
