name: manifests-deploy

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tixbee-github-env # name of the env set in the repo settings
    steps:
      - uses: actions/checkout@v4 # Use latest version of checkout action

        # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      # Get GKE Credentials
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      # Apply manifests
      - name: Apply manifests
        run: kubectl apply -f infra/k8s
      # Here, prod-ssl folder is not included. If any changes are made in prod-ssl folder, we have to manually trigger ssl-config.yaml workflow.
