name: orders-deploy

on:
  push:
    branches:
      - main
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tixbee-github-env
    steps:
      - uses: actions/checkout@v4

      # Login to Docker Hub using the official action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for better build performance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push in a single step
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./orders
          push: true
          tags: khaftab/orders:latest,khaftab/orders:${{ github.sha }}

        # Login to Azure
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get AKS credentials
      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          resource-group: TixBee
          cluster-name: tixbee-cluster

      # Restart deployment
      - name: Restart Deployment
        run: kubectl rollout restart deployment orders-depl
