name: queue-test

on:
  pull_request:
    paths:
      - "queue/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd queue && npm install && npm run test:ci
