name: Setup SSL
on:
  workflow_dispatch: # Manual trigger

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: tixbee-github-env # name of the env set in the repo settings
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          # resource-group: TixBee # yess
          # cluster-name: tixbee-cluster
          resource-group: tixbee-staging
          cluster-name: tixbee-staging

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.yaml

          kubectl wait --namespace cert-manager \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/instance=cert-manager \
            --timeout=180s

      - name: Apply SSL Configurations
        run: kubectl apply -f infra/k8s/prod-ssl
# Before running this workflow, make sure host name in ingress-srv points to the external ip of the ingress controller / cloud load balancder ip.
# kubectl get service -n ingress-nginx
# Grab the external ip and update in DNS provider.
# In case of unssuccessful ssl generation, re running this workflow will not work. We have to see the logs and fix the issue by directly accessing the terminal.
